title: QuizMaker
email: contact@stefanobrogi.it
description: >-
  QuizMaker è un'applicazione web client-side progettata per offrire un'esperienza di quiz interattiva, mobile-first e ADHD-friendly.
baseurl: ""
url: "https://quizmaker.stefanobrogi.it"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

sass:
  quiet_deps: true
  style: compressed

# Exclude from processing
exclude:
  - .jekyll-cache
  - .git/
  - .github/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - scripts/
  - README.md
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md
  - SECURITY.md
  - LICENSE
