blank_issues_enabled: true
contact_links:
  - name: "💬 Discussioni"
    url: "https://github.com/Ste517/QuizMaker/discussions"
    about: "Usa le discussioni per domande generali o per parlare con la community."
